# Generated by Django 2.1.7 on 2019-02-22 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usages', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tap',
            name='card',
        ),
        migrations.RemoveField(
            model_name='tap',
            name='machine',
        ),
        migrations.DeleteModel(
            name='Tap',
        ),
    ]
