# Generated by Django 2.1.7 on 2019-06-14 10:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usage',
            name='machine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='machines.Machine'),
        ),
        migrations.AlterField(
            model_name='usage',
            name='machine_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='machines.Machine_type'),
        ),
        migrations.AlterField(
            model_name='usage',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
