# Generated by Django 2.1.7 on 2019-02-15 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hac', '0002_auto_20190215_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='card_uid',
            field=models.CharField(db_index=True, max_length=8),
        ),
        migrations.AlterField(
            model_name='profile',
            name='nim',
            field=models.CharField(db_index=True, max_length=10),
        ),
    ]
