# Generated by Django 2.1.7 on 2019-02-15 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hac', '0003_auto_20190215_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='card_uid',
            field=models.CharField(db_index=True, max_length=8, unique=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='nim',
            field=models.CharField(db_index=True, max_length=10, unique=True),
        ),
    ]
