# Generated by Django 2.1.7 on 2019-02-15 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hac', '0005_auto_20190215_1511'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usage',
            name='card',
        ),
        migrations.RemoveField(
            model_name='usage',
            name='machine',
        ),
        migrations.DeleteModel(
            name='Usage',
        ),
    ]
